<?php
declare(strict_types=1);

// config.php is generated by bin/setup.sh (see config.example.php for the
// template) — it doesn't exist until you run it, so a deploy without setup
// fails immediately with a clear error instead of using a random timezone.
$configPath = __DIR__ . '/config.php';
if (!is_file($configPath)) {
    http_response_code(500);
    header('Content-Type: text/plain; charset=utf-8');
    echo "Missing configuration: run 'bash bin/setup.sh' from the project root and re-upload webroot/, then retry.\n";
    exit;
}
$mcaConfig = require $configPath;

date_default_timezone_set($mcaConfig['timezone']);

// webroot/api/lib -> webroot/api -> webroot
define('MCA_DATA_DIR', dirname(__DIR__, 2) . '/data');
