<?php
declare(strict_types=1);

// Questo è solo un MODELLO. La copia vera, generata da `php bin/setup.php`
// nella radice del progetto, si chiama config.php e sta nella stessa
// cartella — non è tracciata da git (vedi .gitignore), perché contiene dati
// specifici del tuo deploy.
//
// This is a TEMPLATE only. The real copy, generated by `php bin/setup.php`
// from the project root, is named config.php in this same folder — it is
// not tracked by git (see .gitignore) because it holds deployment-specific
// values.

return [
    // Identificatore di fuso orario PHP valido — elenco completo:
    // https://www.php.net/manual/en/timezones.php
    // Valid PHP timezone identifier — full list at the link above.
    'timezone' => 'Europe/Rome',
];
