<?php
declare(strict_types=1);

// This is a TEMPLATE only. The real copy, generated by `bash bin/setup.sh`
// from the project root, is named config.php in this same folder — it is
// not tracked by git (see .gitignore) because it holds deployment-specific
// values.

return [
    // Valid PHP timezone identifier — full list:
    // https://www.php.net/manual/en/timezones.php
    'timezone' => 'Europe/Rome',
];
